language: go

go:
  - 1.13

env:
  - GO111MODULE=on

branches:
only:
  - master

addons:
  sonarcloud:
    organization: "bytemare-github"
    token:
      secure: ${SONAR_TOKEN}

git:
  depth: false # Sonar doesn't like shallow clones

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
    - os: windows

install:
  - cd app
  - go build crawl.go

script:
  - go run crawl.go https://bytema.re
  - cd ../ && sonar-scanner -X