language: go

go:
  - 1.13
  - tip

env:
  - GO111MODULE=on

branches:
  only:
  - master

addons:
  sonarcloud:
    organization: "bytemare-github"
    token:
      secure: ${SONAR_TOKEN}

git:
  depth: false # Sonar doesn't like shallow clones

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
    - os: windows

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -trace trace.out
  - go test -race -coverprofile=coverage.out -covermode=atomic
  - $GOPATH/bin/goveralls -service=travis-ci
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)