language: go

env:
  - GO111MODULE=on

branches:
  only:
    - dev
    - master

git:
  depth: false # Sonar doesn't like shallow clones

notifications:
  email: false

jobs:
  include:

    - stage : "Static Analysis"
      go: 1.13.x
      os: linux
      dist: trusty
      install:
        - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      script:
        - golangci-lint run ./...

    - stage: "Tests"
      name: "Unit Tests and coverage"
      go: 1.13.x
      addons:
        sonarcloud:
          organization: "bytemare-github"
          token:
            secure: ${SONAR_TOKEN}
      os: linux
      dist: trusty
      install:
        - go get github.com/mattn/goveralls
      script:
        #- go test -v -trace trace.out
        - go test -v -race -coverprofile=coverage.out -covermode=atomic
      after_success:
        - sonar-scanner
        - bash <(curl -s https://codecov.io/bash)
        - $GOPATH/bin/goveralls -service=travis-ci

    - go: 1.12.x
      name: "1.12 / linux"
      os: linux
      dist: trusty
      script: go test -v -race
    - go : 1.12.x
      name: "1.12 / osx"
      os: osx
      script: go test -v -race
    - go : 1.13.x
      name: "1.13 / osx"
      os: osx
      script: go test -v -race
