language: go

go:
  - 1.11
  - 1.12
  - 1.13
  - tip

env:
  - GO111MODULE=on

#branches:
#  only:
#  - dev

addons:
  sonarcloud:
    organization: "bytemare-github"
    token:
      secure: ${SONAR_TOKEN}

git:
  depth: false # Sonar doesn't like shallow clones

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: trusty
      go :
        - 1.13
      before_install:
        - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      after_success:
        - golangci-lint run ./... --enable-all --disable=godox --disable=gochecknoglobals --disable=maligned --disable=gochecknoinits --trace-path=./trace.ci
    - os: osx
    - os: windows
  allow_failures:
    - os: windows
  fast_finish: true

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -trace trace.out
  - go test -v -race -coverprofile=coverage.out -covermode=atomic
  - $GOPATH/bin/goveralls -service=travis-ci

after_success:
  - sonar-scanner
  - bash <(curl -s https://codecov.io/bash)