language: go

go:
  - 1.12
  - 1.13

env:
  - GO111MODULE=on

os:
  - linux
  - windows
  - osx
dist: trusty

branches:
only:
  - master

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        sonarcloud:
          organization: "bytemare-github"
          token:
            secure: ${SONAR_TOKEN}
    - os: osx
    - os: windows


git:
  depth: false # Sonar doesn't like shallow clones

notifications:
  email: false

install:
  - cd app
  - go build crawl.go

script:
  - go run crawl.go https://bytema.re

after_success:
  - sonar-scanner -X