language: go

env:
  - GO111MODULE=on

branches:
  only:
    - dev
    - master

git:
  depth: false # Sonar doesn't like shallow clones

notifications:
  email: false

jobs:
  include:
    - stage : analysis
    - go: 1.13.x
      addons:
        sonarcloud:
          organization: "bytemare-github"
          token:
            secure: ${SONAR_TOKEN}
      os: linux
      dist: trusty
      install:
        - go get github.com/mattn/goveralls
        - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      before_script:
        - golangci-lint run ./...
      after_success:
        - sonar-scanner
        - bash <(curl -s https://codecov.io/bash)
        - $GOPATH/bin/goveralls -service=travis-ci
    - stage: test
    - go: 1.12.x
      os: linux
      dist: trusty
    - go : 1.12.x
      os: osx
    - go : 1.13.x
      os: osx

script:
  - go test -v -trace trace.out
  - go test -v -race -coverprofile=coverage.out -covermode=atomic