# Default configuration for the crawler

# Default crawler values
requests:
  timeout : 10s #specify duration with dimension : 5s, 3m, 2h
  retries : 3

# Log configuration
log:
  do: false
  level: 3
  output: "file" # or "stdout"
  file: "./crawler.log"
  perms: 0600
  type: "text" # or json
