# Default configuration for the crawler

# Default crawler values
requests:
  timeout : 10s #specify duration with dimension : 5s, 3m, 2h
  retries : 3

# Logging configuration
logging:
  do: false
  level: 3
  output: "file" # or "stdout"
  file: "./log-crawler.log"
  perms: 0666
  type: "text" # or json


